baseurl = "https://gitjcc.com/"
title = "gitjcc"
author = "Jesse"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"
enableEmoji = true

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "GitJcc"
  description = "Jesse's Blog, Powered By Hugo & Netlify"
  disableWebFonts = false

[[menu.main]]
  weight = 1
  name   = "Home"
  url    = "/"
[[menu.main]]
  weight = 2
  name   = "Slides"
  url    = "https://slides.gitjcc.com/"
[[menu.main]]
  weight = 3
  name   = "GitHub"
  url    = "https://github.com/gitjcc"
[[menu.main]]
  weight = 4
  name   = "About"
  url    = "/about"
